### ISSUE TITLE
Add version validation to pull requests

### ISSUE THREAD

**Issue by Anut-py** [Anut-py/dime#11]
Create a github actions workflow that runs on pull requests. It should check if the version in package.json isn’t taken. This will prevent creating releases without incrementing the version.

**Comment by lodenrogue** [comment]
Would it also be useful to make sure the version doesn't decrement as well?

**Comment by Anut-py** [comment]
@lodenrogue Yes; basically, just check that the version in package.json doesn’t already exist in npm.
